CREATE TABLE ATTACHMENTS (
  id NUMBER(11),
  user_id VARCHAR2(255),
  label_id NUMBER(10),
  name VARCHAR2(250),
  CONSTRAINT pk_attachements PRIMARY KEY (id)
);

CREATE SEQUENCE ATTACHMENTS_SEQ START WITH 4;
