INSERT ALL
  INTO LOCATIONS VALUES(LOCATIONS_SEQ.NEXTVAL, odessa_city_id, 'Chaikovs''koho Ln', '1')
  INTO LABELS VALUES(LABELS_SEQ.NEXTVAL, 1, LOCATIONS_SEQ.CURRVAL, 'Opera theatre', 5, 46.485435, 30.7403397, TO_DATE('20.10.2016', 'DD.MM.YYYY'))
  INTO CATEGORIES_LABELS VALUES(LABELS_SEQ.CURRVAL, category_id)
  INTO TAGS_LABELS VALUES(LABELS_SEQ.CURRVAL, tag1_id)
  INTO TAGS_LABELS VALUES(LABELS_SEQ.CURRVAL, tag2_id)  
  SELECT
    CITIES.ID AS odessa_city_id,
    CATEGORIES.ID AS category_id,
    TAG1.ID AS tag1_id,
    TAG2.ID AS tag2_id
  FROM
    CITIES, CATEGORIES, TAGS TAG1, TAGS TAG2
  WHERE
    CITIES.NAME = 'Odessa' AND CATEGORIES.NAME = 'Theaters' AND 
    TAG1.NAME = 'Opera' AND TAG2.NAME = 'Buildings';