WITH TAB_TAG_COUNT AS (
SELECT
  TAG_ID,
  1 AS TAG_COUNT
FROM
  TAGS_LABELS
),
TAB_TAG_COUNT_SUM AS
(
SELECT
  TAG_ID,
  SUM(TAG_COUNT) AS TAG_COUNT
FROM
  TAB_TAG_COUNT
GROUP BY
  TAG_ID
),
TAB_TAG_COUNT_SUM_SORTED AS
(
SELECT
  TAG_ID,
  TAG_COUNT
FROM 
  TAB_TAG_COUNT_SUM
ORDER BY
  TAG_COUNT DESC
)
SELECT
  TAGS.NAME AS NAME,
  TAB_TAG_COUNT_SUM_SORTED.TAG_ID AS ID,
  TAB_TAG_COUNT_SUM_SORTED.TAG_COUNT AS TAG_COUNT
FROM 
  TAB_TAG_COUNT_SUM_SORTED, TAGS
WHERE
  ROWNUM <= 30 AND TAGS.ID = TAB_TAG_COUNT_SUM_SORTED.TAG_ID
;