package com.netcracker.queries;

/**
 * @author Yuksi
 */
public interface QueriesSpecification {
    String COUNTRIES_ALL = "SELECT * FROM COUNTRIES";

    String STATES_BY_COUNTRY_ID = "SELECT * FROM STATES WHERE COUNTRY_ID = %1$d";
    String STATES_BY_NAME = "SELECT * FROM STATES WHERE NAME = '%s'";

    String CITIES_BY_NAME = "SELECT * FROM CITIES WHERE NAME = '%s'";

    String LABELS_BY_RECTANGLE = "SELECT * FROM LABELS WHERE COORDINATE_LAT >= %1$.7 AND " +
            "COORDINATE_LAT <= $2$.7 AND COORDINATE_LONG >= %3$.7 AND COORDINATE_LONG <= %4$.7";

    String ATTACHMENTS_BY_LABEL_ID = "SELECT * FROM ATTACHMENTS WHERE LABEL_ID = %1$d";
    String COMMENTS_BY_LABEL_ID = "SELECT * FROM COMMENTS WHERE LABEL_ID = %1$d";
    String CATEGORIES_BY_LABEL_ID = "SELECT * FROM CATEGORIES WHERE ID IN " +
            "(SELECT CATEGORY_ID FROM CATEGORIES_LABELS WHERE LABEL_ID = %1$d)";
    String TAGS_BY_LABEL_ID = "SELECT * FROM TAGS WHERE ID IN " +
            "(SELECT TAG_ID FROM TAGS_LABELS WHERE LABEL_ID = %1$d)";

    String MAP_PROVIDER_BY_NAME = "SELECT * FROM MAP_PROVIDERS WHERE NAME = '%s'";

}
