create table USERCONNECTION
(
USERID         VARCHAR2(255) not null,
PROVIDERID     VARCHAR2(255) not null,
PROVIDERUSERID VARCHAR2(255) not null,
RANK           INTEGER not null,
DISPLAYNAME    VARCHAR2(255),
PROFILEURL     VARCHAR2(512),
IMAGEURL       VARCHAR2(512),
ACCESSTOKEN    VARCHAR2(255) not null,
SECRET         VARCHAR2(255),
REFRESHTOKEN   VARCHAR2(255),
EXPIRETIME     NUMBER(19)
) ;


alter table USERCONNECTION
add primary key (USERID, PROVIDERID, PROVIDERUSERID) ;

create table USER_ACCOUNTS
(
ID         VARCHAR2(255) not null,
EMAIL      VARCHAR2(100) ,
USER_NAME      VARCHAR2(100) not null,
FIRST_NAME VARCHAR2(100) not null,
LAST_NAME  VARCHAR2(100) not null,
ROLE       VARCHAR2(20) not null,
ENABLED    VARCHAR2(1) default 'Y' not null
) ;

alter table USER_ACCOUNTS
add primary key (ID) ;


drop table USER_ACCOUNTS CASCADE CONSTRAINTS;
drop table USERCONNECTION CASCADE CONSTRAINTS;